os: linux
language: android
branch: dev
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-22
    - android-27
    - sys-img-armeabi-v7a-google_apis-22
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-android-support
jdk: oraclejdk8
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - wget https://services.gradle.org/distributions/gradle-4.4-all.zip
  - unzip -qq gradle-4.4-all.zip
  - export GRADLE_HOME=$PWD/gradle-4.4
  - export PATH=$GRADLE_HOME/bin:$PATH
  - git clone https://github.com/flutter/flutter.git -b master
script:
  - ./flutter/bin/flutter -v build apk

after_success:
  - sh set_tags.sh

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Edwin Montoya Jaramillo"
  - git config --local user.email "emonto15@eafit.edu.co"

deploy:
  provider: releases
  api_key: $GH_KEY
  file: "build/app/outputs/apk/app.apk"
  skip_cleanup: true
  prerelease: true
  on:
    branch: dev
    repo: emonto15/memories

cache:
  directories:
    - $HOME/.pub-cache